### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 2, got 0)

### ISSUE THREAD

**Issue by garyvdm** [d-e-s-o/argcomp#1]
With the following file: (intentionally simple to makes sure it wasn't something funny I was doing.)

```
from deso.argcomp import CompletingArgumentParser as ArgumentParser

parser = ArgumentParser()
args = parser.parse_args()
```

I got this error:

```
 # python3 test.py --_complete 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    args = parser.parse_args()
  File "/usr/local/lib/python3.7/dist-packages/deso/argcomp/parser.py", line 390, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deso/argcomp/parser.py", line 445, in parse_args
    return self._parseArgs(super().parse_args, args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/deso/argcomp/parser.py", line 439, in _parseArgs
    return parse_func(args=args, namespace=namespace)
  File "/usr/lib/python3.7/argparse.py", line 1764, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/deso/argcomp/parser.py", line 388, in wrapper
    return getattr(super_, function.__name__)(*args, **kwargs)
  File "/usr/lib/python3.7/argparse.py", line 1796, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 2002, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1942, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1870, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.7/dist-packages/deso/argcomp/parser.py", line 282, in __call__
    index, script, *words = values
ValueError: not enough values to unpack (expected at least 2, got 0)
```

Ubuntu 19.10, Python 3.7.5, argcompd==0.9.0.1

**Comment by d-e-s-o** [comment]
Thanks for the bug report. Unfortunately -- and it saddens me to say that, but at the same time I want to set expectations straight -- I won't be able to provide support for this package. It was an experiment and while I still use it in some of my Python projects (where it works and which in turn are mostly in maintenance mode at best), it's effectively out there as-is with me not having the cycles to care much for it. I leave it up to you to decide whether to use it or not given this statement. I would consider accepting small sized pull requests if you find it useful and want to contribute, though.

That being said, in this particular case, I'd say you may be using it wrong. As the [README](https://github.com/d-e-s-o/argcomp/blob/devel/argcomp/README.md#usage) tries to illustrate, `--_complete` expects a bunch of arguments related to bash-style completion.

Here is your minimal example beefed up a bit:
```patch
--- test.py
+++ test.py
@@ -1,4 +1,7 @@
 from deso.argcomp import CompletingArgumentParser as ArgumentParser

 parser = ArgumentParser()
+parser.add_argument("--foo", action="store_true")
+parser.add_argument("--bar", action="store_true")
+
 args = parser.parse_args()
```

Here it is in action:
```bash
$ python test.py --_complete 1 test.py --f
> --foo
python test.py --_complete 1 test.py --b
> --bar
$ python test.py --_complete 1 test.py --
> --help
> --foo
> --bar
```

This comment should explain why we need `1` there and `test.py`:
```python
class CompleteAction(Action):
  """An action used for completing command line arguments."""
  def __call__(self, parser, namespace, values, option_string=None):
    """Invoke the action to attempt to complete a command line argument."""
    values = list(unescapeDoubleDash(values))

    # The values array we got passed in here contains all arguments as
    # they were passed in to the --_complete option, in our case, the
    # word index ($COMP_CWORD) and words as parsed by the shell
    # ($COMP_WORDS[@]). The first word in the words array is typically
    # the Python script invoked. It might not be if the script was
    # invoked by indirectly by passing it as an argument to the
    # interpreter.
    index, script, *words = values
    index = int(index)

    parser.complete(words[:index])
```

Hope this helps!
